
<?php
$Whatdoing = $_POST['q1'];
$Interestedinexploring = $_POST['q2'];
$Motivates = $_POST['q3'];
$Appointments = $_POST['q4'];
$Important = $_POST['q5'];
$Goals = $_POST['q6'];
$Fname = $_POST['q7'];
$Lname = $_POST['q8'];
$Email = $_POST['q9'];
$Rightnow = $_POST['q10'];
$Time = $_POST['q11'];
$t = $_POST['q14'];
$Prioritize = $_POST['q12'];
$Phone = $_POST['q13'];
$Filename = $_POST['filename'];

    ini_set( 'display_errors', 1 );
    error_reporting( E_ALL );
    $from = "leads@whystraightline.com";
    $to = "terry@straightlinedesignllc.com";
    $subject = "New Lead - " . $Fname . ' ' . $Lname;
    $message = "***START*** \n";
    $message .= "\n";
    $message .= "Part I";
    $message .= "\n";
    $message .= 'Q1. What are you doing now?';
    $message .= "\n";
    $message .= 'A1. ' . $Whatdoing;
    $message .= "\n";
    $message .= 'Q2. Why are you interested in exploring what we do?';
    $message .= "\n";
    $message .= 'A2. ' . $Interestedinexploring;
    $message .= "\n";
    $message .= 'Q3. What is it that motivates you?';
    $message .= "\n";
    $message .= 'A3. ' . $Motivates;
    $message .= "\n";
    $message .= "\n";
    $message .= "Part II";
    $message .= "\n";
    $message .= 'Q1. If you got 10-15 qualified appointments can you manage that well?';
    $message .= "\n";
    $message .= 'A1. ' . $Appointments;
    $message .= "\n";
    $message .= 'Q2. Besides money, what is important to you?';
    $message .= "\n";
    $message .= 'A2. ' . $Important;
    $message .= "\n";
    $message .= 'Q3. What is your short term and long term goals?';
    $message .= "\n";
    $message .= 'A3. ' . $Goals;
    $message .= "\n";
    $message .= "\n";
    $message .= "Part III";
    $message .= "\n";
    $message .= 'Q1. First Name';
    $message .= "\n";
    $message .= 'A1. ' . $Fname;
    $message .= "\n";
    $message .= 'Q2. Last Name';
    $message .= "\n";
    $message .= 'A2. ' . $Lname;
    $message .= "\n";
    $message .= 'Q3. Email';
    $message .= "\n";
    $message .= 'A3. ' . $Email;
    $message .= "\n";
    $message .= 'Q4. Phone';
    $message .= "\n";
    $message .= 'A4. ' . $Phone;
    $message .= "\n";
    $message .= "\n";
    $message .= "Part IV";
    $message .= "\n";
    $message .= 'Q1. Right Now I...';
    $message .= "\n";
    $message .= 'A1. ' . $Rightnow;
    $message .= "\n";
    $message .= 'Q2. Best Time To Call...';
    $message .= "\n";
    $message .= 'A2. On ' . $Time . ' in the ' . $t;
    $message .= "\n";
    $message .= 'Q3. Yes, You Can Count On Me To Prioritize Our Phone Call';
    $message .= "\n";
    $message .= 'A3. ' . $Prioritize;
    $message .= "\n";
    $message .= "\n";
    $message .= "Resume";
    $message .= "\n";
    $message .= "https://apply.whystraightline.com/upload/";
    $message .= $Filename;
    $message .= "\n";
    $message .= "\n ***END***";
    // The content-type header must be set when sending HTML email
    $headers = "MIME-Version: 1.0" . "\r\n";
    $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
    $headers = "From:" . $from;
    if(mail($to,$subject,$message, $headers)) {
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode( true );
    } else {
      echo json_encode( false );
    }
?>